### ISSUE TITLE
Helium IOT and MOBILE stats unavailable

### ISSUE THREAD

**Issue by jooslouw** [enes-oerdek/Home-Assistant-Helium-Integration#12]
Hi Enes

I'm running the latest version 2.5.1. I noticed since 6 Sept 12:00 GMT+2, the Helium Stats IOT and MOBILE are unavailable. All other entities are working fine.

![Screenshot 2023-09-08 at 10 01 42](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/3909940/7de8c7fe-4225-4989-9943-2e9deda3f8cf)

**Comment by jooslouw** [comment]
I forgot to look at the log:

This error originated from a custom integration.

Logger: custom_components.helium_solana.sensors.HeliumStats
Source: custom_components/helium_solana/api/backend.py:17
Integration: Helium Integration (documentation, issues)
First occurred: 09:52:59 (110 occurrences)
Last logged: 11:33:00

Error retrieving helium stats from hotspotty
Traceback (most recent call last):
  File "/config/custom_components/helium_solana/sensors/HeliumStats.py", line 78, in async_update
    response = await self.api.get_data('heliumstats')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/backend.py", line 28, in get_data
    response = await asyncio.to_thread(self.http_client, path, None, 'GET', headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/backend.py", line 17, in http_client
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://solana.oerdek.com/heliumstats

**Comment by enes-oerdek** [comment]
Hello @jooslouw, thanks for providing the error log.
Since two weeks, it seems hotspotty successfully blocked the single request to retrieve the stats from hotspotty. That being the only external data source for this integration, the helium stats no longer work. But another solution is on the way. I had been planning to generate the stats via backend, so that no external sources are needed. Currently the latest stats are "hardcoded" so that existing graphs work until updated data is provided.

I will provide an update, as soon as there is one.

Kind regards
Enes

**Comment by neildotwilliams** [comment]
Hi @enes-oerdek Firstly thanks for this integration. Is there any update to this hotspotty issue?
